before_install:
  - docker pull couchdb:1
  - docker run -d -p 127.0.0.1:5984:5984 couchdb:1
  - docker pull couchdb:2
  - docker run -d -p 127.0.0.1:5985:5984 couchdb:2
go:
  - 1.10.x
go_import_path: github.com/joelnb/sofa
language: go
script:
  - echo "Sleeping to allow the CouchDB server to fully startup"
  - sleep 30
  - env SOFA_TEST_HOST_1=http://127.0.0.1:5984 SOFA_TEST_HOST_2=http://127.0.0.1:5985 go test -v .
  - diff -u <(echo -n) <(gofmt -d *.go)
services:
  - docker
sudo: required
