before_install:
  - docker pull couchdb:1
  - docker run -d -p 127.0.0.1:5984:5984 couchdb:1
go:
  - 1.10.x
go_import_path: github.com/joelnb/sofa
language: go
script:
  - sleep 10
  - env SOFA_TEST_HOST=http://127.0.0.1:5984 go test -v .
  - diff -u <(echo -n) <(gofmt -d *.go)
services:
  - docker
sudo: required
