before_install:
  - docker pull couchdb
  - docker run -d -p 127.0.0.1:5984:5984 couchdb
go:
  - 1.8.x
go_import_path: github.com/joelnb/sofa
language: go
script: env SOFA_TEST_HOST=http://127.0.0.1:5984 go test -v .
services:
  - docker
sudo: required
